### ISSUE TITLE
 How to measure speed with the library ?

### ISSUE THREAD

**Issue by pyzimmer** [sparkfun/SparkFun_Qwiic_XM125_Arduino_Library#2]
How to measure speed with the library ? Thanks

**Comment by edspark** [comment]
Velocity is a result of distance/time. I would subtract the current distance with the previous distance and then divide that by the time between the two samples.

**Comment by pyzimmer** [comment]
@edspark thank you. So, how to get the sensor timestamp ? Because the sensor does not have constant framerate.

**Comment by edspark** [comment]
If you're using Arduino, you can use [millis()](https://reference.arduino.cc/reference/en/language/functions/time/millis/) to save time at each sample.
